logging:
  level:
    org.springframework: INFO
    com.netflix.discovery: DEBUG
    com.netflix.eureka: DEBUG

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/users
    serverName : localhost
    username: sa
    password : password

  jpa:
    generate-ddl: true
    show_sql: true
    hibernate:
      ddl_auto : create-drop

  h2:
    console:
      enabled: true
      path: /h2-console

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}-${spring.profiles.active}-${server.port}
  client:
    service-url:
      default-zone: http://localhost:8761 # workaround
    register-with-eureka: true
    fetch-registry: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
